/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Maribel
 */
public class VistaAsignaturasPlanComun extends javax.swing.JFrame {

    /**
     * Creates new form VistaAsignaturasPlanComun
     */
    public VistaAsignaturasPlanComun() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonCalculo1 = new javax.swing.JButton();
        BotonAlgebra1 = new javax.swing.JButton();
        BotonFisica1 = new javax.swing.JButton();
        BotonMetodosEstudio = new javax.swing.JButton();
        BotonIntroIng = new javax.swing.JButton();
        BotonTDP = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BotonAlgebra2 = new javax.swing.JButton();
        BotonFisica2 = new javax.swing.JButton();
        BotonProgra = new javax.swing.JButton();
        BotonQuimica = new javax.swing.JButton();
        BotonCalculo2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        BotonAnalisisEstadistico = new javax.swing.JButton();
        BotonCalculo3 = new javax.swing.JButton();
        BotonIngles2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        BotonIngles3 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        BotonEcono = new javax.swing.JButton();
        BotonEcua = new javax.swing.JButton();
        BotonElectro = new javax.swing.JButton();
        BotonIngles1 = new javax.swing.JButton();
        BotonComunicacionEfectiva = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        BotonIngles4 = new javax.swing.JButton();
        BotonAtras = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));

        BotonCalculo1.setText("Calculo1");
        BotonCalculo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCalculo1ActionPerformed(evt);
            }
        });

        BotonAlgebra1.setText("Algebra1");
        BotonAlgebra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAlgebra1ActionPerformed(evt);
            }
        });

        BotonFisica1.setText("Fisica1");
        BotonFisica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFisica1ActionPerformed(evt);
            }
        });

        BotonMetodosEstudio.setText("Metodos de estudio");
        BotonMetodosEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMetodosEstudioActionPerformed(evt);
            }
        });

        BotonIntroIng.setText("Intro a la ing");
        BotonIntroIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIntroIngActionPerformed(evt);
            }
        });

        BotonTDP.setText("TDP");
        BotonTDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTDPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonMetodosEstudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonFisica1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonAlgebra1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonCalculo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonIntroIng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonTDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(BotonCalculo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonAlgebra1)
                .addGap(5, 5, 5)
                .addComponent(BotonFisica1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonMetodosEstudio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonIntroIng)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonTDP)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 173, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BotonAlgebra2.setText("Algebra2");
        BotonAlgebra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAlgebra2ActionPerformed(evt);
            }
        });

        BotonFisica2.setText("Fisica2");
        BotonFisica2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFisica2ActionPerformed(evt);
            }
        });

        BotonProgra.setText("Fundamentos de progra");
        BotonProgra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPrograActionPerformed(evt);
            }
        });

        BotonQuimica.setText("Quimica general");
        BotonQuimica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonQuimicaActionPerformed(evt);
            }
        });

        BotonCalculo2.setText("Calculo2");
        BotonCalculo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCalculo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonQuimica, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonFisica2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonProgra)
                    .addComponent(BotonAlgebra2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonCalculo2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(BotonCalculo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonAlgebra2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonFisica2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonProgra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonQuimica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));

        BotonAnalisisEstadistico.setText("Analisis estadistico");
        BotonAnalisisEstadistico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnalisisEstadisticoActionPerformed(evt);
            }
        });

        BotonCalculo3.setText("Calculo 3");
        BotonCalculo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCalculo3ActionPerformed(evt);
            }
        });

        BotonIngles2.setText("Ingles 2");
        BotonIngles2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngles2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonIngles2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonCalculo3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAnalisisEstadistico))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(BotonAnalisisEstadistico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonCalculo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonIngles2)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));

        BotonIngles3.setText("Ingles 3");
        BotonIngles3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngles3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(BotonIngles3)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(BotonIngles3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 173, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BotonEcono.setText("Fund. de economia");
        BotonEcono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEconoActionPerformed(evt);
            }
        });

        BotonEcua.setText("Ecuaciones diferenciales");
        BotonEcua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEcuaActionPerformed(evt);
            }
        });

        BotonElectro.setText("Electro");
        BotonElectro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonElectroActionPerformed(evt);
            }
        });

        BotonIngles1.setText("Ingles 1");
        BotonIngles1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngles1ActionPerformed(evt);
            }
        });

        BotonComunicacionEfectiva.setText("Comunicacion efectiva");
        BotonComunicacionEfectiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComunicacionEfectivaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonEcono, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonComunicacionEfectiva, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonIngles1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonElectro, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonEcua, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(BotonEcono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonEcua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonElectro)
                .addGap(11, 11, 11)
                .addComponent(BotonComunicacionEfectiva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonIngles1)
                .addContainerGap())
        );

        jPanel14.setBackground(new java.awt.Color(255, 163, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BotonIngles4.setText("Ingles 4");
        BotonIngles4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngles4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(BotonIngles4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(BotonIngles4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BotonAtras.setText("Atras");

        BotonSalir.setText("Salir");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Asignaturas area plan comun");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BotonAtras)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(227, 227, 227)
                        .addComponent(BotonSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonSalir)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonAtras))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCalculo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCalculo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCalculo1ActionPerformed

    private void BotonAlgebra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAlgebra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAlgebra1ActionPerformed

    private void BotonFisica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFisica1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonFisica1ActionPerformed

    private void BotonMetodosEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMetodosEstudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMetodosEstudioActionPerformed

    private void BotonIntroIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIntroIngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonIntroIngActionPerformed

    private void BotonTDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonTDPActionPerformed

    private void BotonAlgebra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAlgebra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAlgebra2ActionPerformed

    private void BotonFisica2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFisica2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonFisica2ActionPerformed

    private void BotonPrograActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPrograActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPrograActionPerformed

    private void BotonQuimicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonQuimicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonQuimicaActionPerformed

    private void BotonCalculo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCalculo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCalculo2ActionPerformed

    private void BotonEconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEconoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEconoActionPerformed

    private void BotonEcuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEcuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEcuaActionPerformed

    private void BotonElectroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonElectroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonElectroActionPerformed

    private void BotonIngles1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngles1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonIngles1ActionPerformed

    private void BotonComunicacionEfectivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComunicacionEfectivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonComunicacionEfectivaActionPerformed

    private void BotonAnalisisEstadisticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnalisisEstadisticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAnalisisEstadisticoActionPerformed

    private void BotonCalculo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCalculo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCalculo3ActionPerformed

    private void BotonIngles2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngles2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonIngles2ActionPerformed

    private void BotonIngles3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngles3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonIngles3ActionPerformed

    private void BotonIngles4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngles4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonIngles4ActionPerformed

    /**
     * @param args the command line arguments
     */

    /**
     * @param args the command line arguments
     */
    public JButton getBotonCalculo1() {
        return BotonCalculo1;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAlgebra1;
    private javax.swing.JButton BotonAlgebra2;
    private javax.swing.JButton BotonAnalisisEstadistico;
    private javax.swing.JButton BotonAtras;
    private javax.swing.JButton BotonCalculo1;
    private javax.swing.JButton BotonCalculo2;
    private javax.swing.JButton BotonCalculo3;
    private javax.swing.JButton BotonComunicacionEfectiva;
    private javax.swing.JButton BotonEcono;
    private javax.swing.JButton BotonEcua;
    private javax.swing.JButton BotonElectro;
    private javax.swing.JButton BotonFisica1;
    private javax.swing.JButton BotonFisica2;
    private javax.swing.JButton BotonIngles1;
    private javax.swing.JButton BotonIngles2;
    private javax.swing.JButton BotonIngles3;
    private javax.swing.JButton BotonIngles4;
    private javax.swing.JButton BotonIntroIng;
    private javax.swing.JButton BotonMetodosEstudio;
    private javax.swing.JButton BotonProgra;
    private javax.swing.JButton BotonQuimica;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonTDP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    public void agregarListener(ActionListener f){
        BotonCalculo1.addActionListener(f);
    }

}
