/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Maribel
 */
public class VistaBibliotecaCentral extends javax.swing.JFrame {

    /**
     * Creates new form VistaBibliotecaCentral
     */
    public VistaBibliotecaCentral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IniciarGato = new javax.swing.JButton();
        IniciarAhorcado = new javax.swing.JButton();
        IniciarBuscaminas = new javax.swing.JButton();
        IniciarAdivina = new javax.swing.JButton();
        IniciarPix = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Atras = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Biblioteca Central");

        IniciarGato.setText("Tres en raya");

        IniciarAhorcado.setText("Ahorcado");

        IniciarBuscaminas.setText("Buscaminas");

        IniciarAdivina.setText("Adivina la palabra");

        IniciarPix.setText("Pix and Pix");

        Salir.setText("Salir");

        Atras.setText("Atras");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(IniciarGato)
                        .addGap(53, 53, 53)
                        .addComponent(IniciarAhorcado)
                        .addGap(52, 52, 52)
                        .addComponent(IniciarBuscaminas)
                        .addGap(55, 55, 55)
                        .addComponent(IniciarAdivina))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                                .addComponent(Salir))
                            .addComponent(IniciarPix))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Atras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Salir))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IniciarGato)
                    .addComponent(IniciarAhorcado)
                    .addComponent(IniciarBuscaminas)
                    .addComponent(IniciarAdivina))
                .addGap(100, 100, 100)
                .addComponent(IniciarPix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(Atras)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JButton getAtras() {
        return Atras;
    }

    public void setAtras(JButton Atras) {
        this.Atras = Atras;
    }

    public JButton getIniciarAdivina() {
        return IniciarAdivina;
    }

    public void setIniciarAdivina(JButton IniciarAdivina) {
        this.IniciarAdivina = IniciarAdivina;
    }

    public JButton getIniciarAhorcado() {
        return IniciarAhorcado;
    }

    public void setIniciarAhorcado(JButton IniciarAhorcado) {
        this.IniciarAhorcado = IniciarAhorcado;
    }

    public JButton getIniciarBuscaminas() {
        return IniciarBuscaminas;
    }

    public void setIniciarBuscaminas(JButton IniciarBuscaminas) {
        this.IniciarBuscaminas = IniciarBuscaminas;
    }

    public JButton getIniciarGato() {
        return IniciarGato;
    }

    public void setIniciarGato(JButton IniciarGato) {
        this.IniciarGato = IniciarGato;
    }

    public JButton getIniciarPix() {
        return IniciarPix;
    }

    public void setIniciarPix(JButton IniciarPix) {
        this.IniciarPix = IniciarPix;
    }

    public JButton getSalir() {
        return Salir;
    }

    public void setSalir(JButton Salir) {
        this.Salir = Salir;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton IniciarAdivina;
    private javax.swing.JButton IniciarAhorcado;
    private javax.swing.JButton IniciarBuscaminas;
    private javax.swing.JButton IniciarGato;
    private javax.swing.JButton IniciarPix;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
public void agregarListener(ActionListener f){
       this.Atras.addActionListener(f);
       this.IniciarAdivina.addActionListener(f);
       this.IniciarAhorcado.addActionListener(f);
       this.IniciarBuscaminas.addActionListener(f);
       this.IniciarGato.addActionListener(f);
       this.IniciarPix.addActionListener(f);
       this.Salir.addActionListener(f);
       
   }
}
