/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VistaCombateCortoRango extends javax.swing.JFrame {

    /**
     * Creates new form VistaCombateCortoRango
     */
    public VistaCombateCortoRango() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonAlto = new javax.swing.JButton();
        botonMedio = new javax.swing.JButton();
        botonBajo = new javax.swing.JButton();
        botonEspecial = new javax.swing.JButton();
        secuenciaElegida = new javax.swing.JLabel();
        secuenciaCpu = new javax.swing.JLabel();
        labelSecuenciaCPUConstante = new javax.swing.JLabel();
        labelSecuenciaCPU = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonAlto.setText("Ataque Alto");
        botonAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAltoActionPerformed(evt);
            }
        });

        botonMedio.setText("Ataque Medio");

        botonBajo.setText("Ataque Bajo");

        botonEspecial.setText("Ataque Especial");

        secuenciaElegida.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        secuenciaElegida.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        labelSecuenciaCPUConstante.setText("Secuencia CPU:");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(secuenciaElegida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(secuenciaCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonAlto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonMedio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonBajo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonEspecial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(73, 73, 73)
                        .addComponent(btnOk)
                        .addGap(0, 285, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(labelSecuenciaCPUConstante)
                        .addGap(18, 18, 18)
                        .addComponent(labelSecuenciaCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSecuenciaCPUConstante)
                    .addComponent(labelSecuenciaCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(secuenciaCpu, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(secuenciaElegida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(botonAlto)
                .addGap(18, 18, 18)
                .addComponent(botonMedio)
                .addGap(18, 18, 18)
                .addComponent(botonBajo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonEspecial)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOk)
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAltoActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    

    public JButton getBotonAlto() {
        return botonAlto;
    }

    public JButton getBotonBajo() {
        return botonBajo;
    }

    public JButton getBotonEspecial() {
        return botonEspecial;
    }

    public JButton getBotonMedio() {
        return botonMedio;
    }

    public JLabel getSecuenciaCpu() {
        return secuenciaCpu;
    }

    public void setSecuenciaCpu(JLabel secuenciaCpu) {
        this.secuenciaCpu = secuenciaCpu;
    }

    public JLabel getSecuenciaElegida() {
        return secuenciaElegida;
    }

    public void setSecuenciaElegida(String secuenciaElegida) {
        this.secuenciaElegida.setText(secuenciaElegida);
       
    }

    public JLabel getLabelSecuenciaCPU() {
        return labelSecuenciaCPU;
    }

    public void setLabelSecuenciaCPU(String secuenciaCPU) {
        this.labelSecuenciaCPU.setText(secuenciaCPU);
    }

    public JButton getBtnOk() {
        return btnOk;
    }
    
        
    
    public void mostrarVentanaSecuenciaIncompleta(){
        JOptionPane.showMessageDialog(null, "La lista de ataques seleccionados no contiene 7 elementos.",   "No hay ataque suficiente",
        JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void mostrarVentanaFinal(String mensaje, String titulo){
        JOptionPane.showMessageDialog(null, mensaje,   titulo,
        JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }
    
    public void mostrarVentanaAtaqueInsuficiente(){
        JOptionPane.showMessageDialog(null, "No hay suficiente ataque del seleccionado",   "No hay ataque suficiente",
        JOptionPane.INFORMATION_MESSAGE);
    }
        
    public void mostrarVentanaListaCompleta(){
        JOptionPane.showMessageDialog(null, "Ya seleccionaste el maximo de ataques",   "Maximo alcanzado",
        JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAlto;
    private javax.swing.JButton botonBajo;
    private javax.swing.JButton botonEspecial;
    private javax.swing.JButton botonMedio;
    private javax.swing.JButton btnOk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelSecuenciaCPU;
    private javax.swing.JLabel labelSecuenciaCPUConstante;
    private javax.swing.JLabel secuenciaCpu;
    private javax.swing.JLabel secuenciaElegida;
    // End of variables declaration//GEN-END:variables

    public void agregarListener(ActionListener f){
    botonAlto.addActionListener(f);
    botonBajo.addActionListener(f);
    botonEspecial.addActionListener(f);
    botonMedio.addActionListener(f);
    btnOk.addActionListener(f);
    }
}
