/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Benxamin
 */
public class VistaPreBatalla extends javax.swing.JFrame {
    DefaultListModel<String> model;
    DefaultListModel<String> modelo; 
    
    /**
     * Creates new form VistaPreBatalla
     */
    public VistaPreBatalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaPersonajesDisponibles = new javax.swing.JList<>();
        labelPersonajesDisponibles = new javax.swing.JLabel();
        labelPersonajesSeleccionados = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPersonajesSeleccionados = new javax.swing.JList<>();
        botonQuitar = new javax.swing.JButton();
        labelAtaque = new javax.swing.JLabel();
        labelInformacionPersonajeFijo = new javax.swing.JLabel();
        botonAgregar = new javax.swing.JButton();
        botonIniciarBatalla = new javax.swing.JButton();
        labelDefensa = new javax.swing.JLabel();
        labelVida = new javax.swing.JLabel();
        labelNivel = new javax.swing.JLabel();
        botonObtenerInformacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaPersonajesDisponibles.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaPersonajesDisponibles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaPersonajesDisponibles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaPersonajesDisponiblesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaPersonajesDisponibles);

        labelPersonajesDisponibles.setText("Personajes disponibles:");

        labelPersonajesSeleccionados.setText("Personajes seleccionados:");

        listaPersonajesSeleccionados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaPersonajesSeleccionados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listaPersonajesSeleccionados);

        botonQuitar.setText("Quitar");
        botonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarActionPerformed(evt);
            }
        });

        labelAtaque.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelInformacionPersonajeFijo.setText("Informacion:");

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonIniciarBatalla.setText("Iniciar Batalla");
        botonIniciarBatalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarBatallaActionPerformed(evt);
            }
        });

        botonObtenerInformacion.setText("Obtener informacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPersonajesDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(botonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonObtenerInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPersonajesSeleccionados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(botonQuitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelInformacionPersonajeFijo)
                    .addComponent(labelAtaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDefensa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelVida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonIniciarBatalla, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPersonajesDisponibles)
                    .addComponent(labelPersonajesSeleccionados)
                    .addComponent(labelInformacionPersonajeFijo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelVida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelNivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(botonQuitar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(botonAgregar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonIniciarBatalla, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonObtenerInformacion))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonQuitarActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void listaPersonajesDisponiblesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaPersonajesDisponiblesValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listaPersonajesDisponiblesValueChanged

    private void botonIniciarBatallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarBatallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonIniciarBatallaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaPreBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaPreBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaPreBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaPreBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaPreBatalla().setVisible(true);
//            }
//        });
//    }

    public void setListaPersonajesDisponibles(ArrayList<String> lista) {
        String[] array = new String[lista.size()];
        lista.toArray(array);
        this.listaPersonajesDisponibles.setListData(array);
    }

    public void setListaPersonajesSeleccionados(ArrayList<String> lista) {
        String[] array = new String[lista.size()];
        lista.toArray(array);
        this.listaPersonajesSeleccionados.setListData(array);
    }

    public String obtenerSeleccionPersonajesDisponibles(){
        return listaPersonajesDisponibles.getSelectedValue();
    }
    
    public String obtenerSeleccionPersonajesSeleccionados(){
        return listaPersonajesSeleccionados.getSelectedValue();
    }
    
    public void añadirListenerLista(ListSelectionListener sl){
        this.listaPersonajesDisponibles.addListSelectionListener(sl);
        this.listaPersonajesSeleccionados.addListSelectionListener(sl);
    
    }
    public void añadirListenerBotones(ActionListener al){
        this.botonAgregar.addActionListener(al);
        this.botonQuitar.addActionListener(al);
        this.botonObtenerInformacion.addActionListener(al);
        this.botonIniciarBatalla.addActionListener(al);
    }

    public JButton getBotonAgregar() {
        return botonAgregar;
    }

    public JButton getBotonQuitar() {
        return botonQuitar;
    }
    
    public int obtenerPosicionElementoPersonajesSeleccionados(){
        return listaPersonajesSeleccionados.getSelectedIndex();
    }
    
    public int obtenerPosicionElementoPersonajesDisponibles(){
        return listaPersonajesDisponibles.getSelectedIndex();
    }
    
    public void quitarElementoSeleccionados(int numero){
        listaPersonajesSeleccionados.remove(numero);
    }
    
    public void quitarElementoDisponible(int numero){
        listaPersonajesDisponibles.remove(numero);
    }
    
    public void agregarElementoListaSeleccionados(String palabra){
       // listaPersonajesSeleccionados.addElement(palabra);
    }
    
    public void agregarElementoListaDisponibles(){}
    
    public void actualizarListaDisponibles(ArrayList<String> lista){
        model = new DefaultListModel<>();
        for(String e : lista){
             model.addElement(e);
        }
        this.listaPersonajesDisponibles.setModel(model);
        //this.listaPersonajesDisponibles.setSelectedIndex(0);
    }
    
    public void actualizarListaSeleccionados(ArrayList<String> lista){
        modelo= new DefaultListModel<>();
        for (String e : lista){
            modelo.addElement(e);
        }
        this.listaPersonajesSeleccionados.setModel(modelo);
    }
    
    public void mostrarVentana(String mensaje, String titulo){
        JOptionPane.showMessageDialog(null, mensaje, titulo,
        JOptionPane.INFORMATION_MESSAGE);
    }

    public String getLabelAtaque() {
        return labelAtaque.getText();
    }

    public void setLabelAtaque(String texto) {
        labelAtaque.setText(texto);
    }

    public String getLabelDefensa() {
        return labelDefensa.getText();
    }

    public void setLabelDefensa(String texto) {
        labelDefensa.setText(texto);
    }

    public String getLabelNivel() {
        return labelNivel.getText();
    }

    public void setLabelNivel(String texto) {
        labelNivel.setText(texto);
    }

    public String getLabelVida() {
        return labelVida.getText();
    }

    public void setLabelVida(String texto) {
        labelVida.setText(texto);
    }

    
    public void borrarSeleccionDisponibles(){
        listaPersonajesDisponibles.clearSelection();
    }
//    public DefaultListModel<String> getModel() {
//        return model;
//    }
//    
//    public DefaultListModel<String> obtenerModeloSeleccionado(){
//        if
//        
//    }
    
    public JButton getBotonObtenerInformacion() {
        return botonObtenerInformacion;
    }
    
    public void seleccionarIndice(int numero){
        this.listaPersonajesDisponibles.setSelectedIndex(numero);
    }

    public JButton getBotonIniciarBatalla() {
        return botonIniciarBatalla;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonIniciarBatalla;
    private javax.swing.JButton botonObtenerInformacion;
    private javax.swing.JButton botonQuitar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAtaque;
    private javax.swing.JLabel labelDefensa;
    private javax.swing.JLabel labelInformacionPersonajeFijo;
    private javax.swing.JLabel labelNivel;
    private javax.swing.JLabel labelPersonajesDisponibles;
    private javax.swing.JLabel labelPersonajesSeleccionados;
    private javax.swing.JLabel labelVida;
    private javax.swing.JList<String> listaPersonajesDisponibles;
    private javax.swing.JList<String> listaPersonajesSeleccionados;
    // End of variables declaration//GEN-END:variables
}
